version: 2
updates:
  - package-ecosystem: 'maven'
    directory: '/backend'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 0

  - package-ecosystem: 'npm'
    directory: '/backend'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 0
    
  - package-ecosystem: 'npm'
    directory: '/ionic-app'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 0
